const unit1 = {
    "provide": "공급하다, 준비하다",
    "develop": "개발하다, 발달하다",
    "service": "서비스, 봉사, 공공 업무",
    "inform": "알리다, 통지하다",
    "relationship": "관계",
    "improve": "향상시키다, 향상하다",
    "individual": "개인, 개인의, 개인적인, 각각의",
    "require": "필요로 하다, 요구하다",
    "advise": "조언하다, 충고하다",
    "social": "사회의, 사교적인",
    "amount": "총액, 총계, 양, 총계가 ~이 되다",
    "behave": "(예의바르게) 행동하다",
    "employ": "고용하다, 기술, 방법등을 쓰다",
    "attitude": "태도, 입장",
    "research": "연구, 연구하다, 조사하다",
    "audience": "청중, 관객",
    "volunteer": "자원봉사, 지원자, 자발적으로 ~하다",
    "influence": "영향, 영향을 미치는 것(사람), 영향을 끼치다",
    "terrible": "끔찍한, 무서운",
    "opportunity": "기회",
    "ability": "능력",
    "expense": "비용, 지출",
    "local": "지방의, 지역의, 장소의",
    "involve": "포함하다, 관련되다, (사건 등에) 말려들게 하다",
    "stress": "강조, 스트레스, 강조하다, 압력을 주다",
    "therefore": "그러므로, 그 결과",
    "positive": "긍정적인, 확신하는",
    "average": "평균, 평균의, 평균~이다",
    "ride": "탈것을 타다, 타기, 타고가기",
    "encourage": "촉구하다, 격려하다",
    "determine": "결심하다, 결정하다",
    "international": "국제의, 국제적인",
    "consume": "소비하다, 먹다, 마시다",
    "impress": "깊은 인상을 주다, 감동시키다",
    "object": "물체, 목표, 반대하다",
    "available": "이용하능한, 쓸모있는",
    "contain": "함유하다, 포함하다, 억제하다",
    "recognize": "인지하다, 인정하다",
    "material": "재료, 물질, 물질의",
    "comfort": "편안하게 하다, 위로하다, 편안, 위로"
};
const unit2 = {
    "emotion": "감정",
    "amaze": "놀라게 하다",
    "reduce": "줄이다, 낮추다",
    "discover": "발견하다",
    "decide": "결심하다, 결정하다",
    "benefit": "이익, 이익이 되다",
    "affect": "영향, 영향을 미치는 것(사람), 영향을 끼치다",
    "level": "수준, 수평, 수평의 , 평평하게 하다",
    "chemistry": "화학, 교감",
    "immediate": "직접의, 즉각적인",
    "thus": "그러므로, 따라서",
    "proper": "적절한, 알맞은",
    "performance": "공연, 성적, 성과",
    "essence": "(사물의) 본질, 정수",
    "economic": "경제의, 경제학의",
    "cell": "세포, 작은 방, 독방",
    "focus": "초점, 집중하다",
    "issue": "논란거리, 발행, 발행물, 발행하다",
    "participate": "참여하다, 참가하다(in)",
    "demand": "요구하다, 수요",
    "occur": "(사건이)일어나다, 발생하다",
    "complex": "복잡한, 복합체",
    "define": "정의하다, 한계 짓다, 한정하다",
    "proud": "자랑스러워하는, 자만하는",
    "aware": "인지하는, 알고 있는",
    "contact": "접촉, 접촉하다",
    "profession": "직업, 직종",
    "detail": "세부, 상술하다",
    "approach": "접근하다, 접근",
    "career": "직업, 경력",
    "package": "꾸러미, 포장, 포장하다",
    "disappear": "사라지다",
    "novel": "(장편)소설, 참신한",
    "secure": "안전한, 안전하게 하다, 확보하다",
    "fashion": "유행, 패션, 방식, 만들어내다",
    "despite": "~에도 불구하고",
    "background": "배경, 배경 지식, 이유",
    "solution": "해결, 해결책, 용액",
    "generate": "일으키다, 발생시키다",
    "eventually": "결국"
};
const unit3 = {
    "decrease": "줄다[감소하다], 줄이다, 감소",
    "recycle": "재활용하다",
    "desire": "욕망, 욕구, 바라다",
    "balance": "균형, 은행 잔고, 균형을 이루다",
    "negative": "부정적인",
    "follow": "따라가다, (규칙을) 따르다",
    "account": "은행 계좌, 이야기, 설명하다",
    "publish": "발표하다, 출판하다",
    "occasion": "경우, 특별한 일",
    "replace": "대체하다",
    "constant": "일정한, 불변의, (수학에서의) 상수",
    "expert": "전문가",
    "term": "기간, 학기, 용어",
    "relieve": "경감하다, 안도시키다",
    "describe": "묘사하다, 표현하다",
    "biology": "생물학",
    "due": "만기의, ~하기로 되어 있는",
    "equipment": "장치, 장비",
    "congratulate": "축하하다",
    "birth": "탄생",
    "compose": "구성하다, 작곡하다, 작문하다",
    "genius": "천재, 천재성",
    "reflect": "반영하다, 반사하다, 숙고하다",
    "cause": "~의 원인이 되다, 야기하다, 원인",
    "frequent": "빈번한, (장소·모임에) 자주 가다",
    "factor": "요인, 요소",
    "extreme": "극단의, 극단",
    "tend": "(~하는) 경향이 있다 (to), 돌보다",
    "politics": "정치, 정치학",
    "insist": "주장하다",
    "extend": "연장하다, 넓히다",
    "lonely": "외로운",
    "habitat": "서식지, 주거지",
    "mental": "정신의",
    "steady": "안정된, 한결같은, 꾸준한",
    "exchange": "교환하다",
    "active": "활동적인, 적극적인",
    "species": "(생물 분류상의) 종",
    "athletic": "운동의, 운동 경기의",
    "dental": "치아의"
};
const unit4 = {
    "delight": "기쁨, 기쁘게 하다",
    "confident": "자신 있는",
    "gradually": "점차, 서서히",
    "shadow": "그림자, 그늘지게 하다",
    "access": "접근, 이용, 접근하다",
    "announce": "발표하다, 알리다",
    "allow": "허락하다. 인정하다",
    "firm": "확고한, 단단한, 회사",
    "vary": "바꾸다, 변하다, 다르다",
    "injure": "상처를 입히다, 손상시키다",
    "permit": "허용하다, 허락하다",
    "response": "응답, 반응",
    "threat": "위협, 협박",
    "electricity": "전기",
    "disabled": "장애를 가진, 무능력하게 된",
    "lack": "부족, ~이 부족하다",
    "signify": "의미하다, 중요하다",
    "concentrate": "집중하다",
    "emphasize": "강조하다",
    "astronomy": "천문학",
    "flood": "홍수, 범람시키다",
    "fuel": "연료, 연료를 가하다",
    "manufacture": "제조하다, 제조(업), 제품",
    "movement": "움직임, 운동",
    "capable": "~을 할 수 있는, 유능한",
    "combine": "결합시키다, 겸비하다",
    "gene": "유전자",
    "increase": "(수량이)늘다, 증가, 이자",
    "victim": "희생, 희생자",
    "pressure": "압력, 압박, 압력을 가하다",
    "accompany": "동반(동행)하다, 수반하다",
    "frustrate": "좌절시키다",
    "construct": "건설하다",
    "dwindle": "점점 줄어들다, 저하되다",
    "commerce": "상업, 교역",
    "entertain": "즐겁게 하다",
    "predict": "예언하다, 예측하다",
    "apologize": "사과하다",
    "sight": "시야, 광경, 시력",
    "quantity": "양(量)"
};
const unit5 = {
    "conclude": "결론짓다, 끝내다",
    "donate": "기부하다",
    "personality": "개성, 성격, 특색",
    "struggle": "싸우다, 노력하다, 투쟁, 노력",
    "advantage": "유리한 점, 이익",
    "variety": "다양, 다양성",
    "enable": "가능하게 하다",
    "instruction": "지시, 제품 사용 설명서, 가르침",
    "assume": "추정하다, (태도 등을)취하다",
    "attempt": "시도하다, 시도",
    "incredible": "믿을 수 없는, (믿기 어려울 만큼)굉장한",
    "feature": "특징, 특집 기사, 얼굴 생김새, ~을 특징으로 하다, 주연하다",
    "confuse": "혼동하다, 혼란시키다",
    "electronic": "전자의",
    "absorb": "흡수하다, (사람, 마음을)열중시키다",
    "indicate": "가리키다, 나타내다",
    "analyze": "분석하다",
    "stock": "재고품, 저장, 가축, 저장하다, (물품을) 들여놓다",
    "resident": "거주자",
    "labor": "노동, 산고, 노동하다",
    "remark": "의견을 말하다, ~에 주목하다, 의견, 주목",
    "moral": "도덕적인",
    "embarrassed": "당황한",
    "claim": "주장하다, 요구, 주장",
    "reasonable": "논리적인, 분별력이 있는",
    "interrupt": "방해하다, 중단하다",
    "discount": "할인, 할인하다",
    "creature": "생물, 피조물",
    "heal": "치료하다, 낫게하다",
    "establish": "설립하다, 확립하다, 제정하다",
    "revolution": "혁명, 갑작스런 변화, 회전",
    "criticize": "비난하다",
    "convince": "확신시키다, 납득시키다",
    "efficient": "효율적인, 유능한",
    "stranger": "낯선 사람, 문외한",
    "tide": "조수, 흐름",
    "obtain": "획득하다, 통용되다, 행해지다",
    "assist": "도움을 주다",
    "disaster": "재앙, 재난, 재해",
    "terrific": "굉장한, 훌륭한"
};
const unit6 = {
    "specific": "구체적인, 특정한",
    "react": "반응하다, 반작용하다",
    "independent": "독립적인",
    "theory": "이론",
    "qualify": "자격을 얻다",
    "consider": "숙고하다, 고려하다",
    "recall": "상기하다, 철회하다, 회수하다, 상기, 철회, 회수",
    "risk": "위험, 위험을 감수하다",
    "treatment": "취급, 대우, 치료, 치료법",
    "engage": "관여하다, 약속하다, 약혼하다",
    "motivate": "동기를 부여하다",
    "clue": "실마리, 단서",
    "cancer": "암, 악성 종양",
    "elder": "나이가 위인, 연장자",
    "depress": "우울하게 하다, 의기소침(낙담)하게 하다",
    "fascinate": "매료시키다, 마음을 빼앗다",
    "violent": "난폭한, 폭력적인",
    "alarm": "놀람, 경보",
    "edge": "가장자리, 유리함, 날카로움",
    "deserve": "~받을 가치가 있다, ~할 만하다",
    "route": "길, 통로, 향로",
    "psychology": "심리, 심리학",
    "passion": "열정",
    "import": "수입하다, 의미하다, 수입",
    "purchase": "구매하다, 구매",
    "conscience": "양심",
    "pose": "자세를 취하다, 문제를 제기하다, 자세",
    "length": "길이",
    "severe": "심한, 엄격한",
    "decade": "10년, 10년간",
    "occupy": "(시간, 장소를) 차지하다, 전념하다",
    "acquire": "습득하다",
    "interact": "상호 작용하다",
    "brief": "간단한, 간단한 보고, 간단히 알리다",
    "observe": "관찰하다, ~을 보다, 준수하다",
    "poetry": "시, 운문",
    "salary": "급료, 봉급",
    "grain": "곡물, 낟알",
    "meaningful": "의미 있는, 의미심장한",
    "weed": "잡초, 잡초를 제거하다"
};
const unit7 = {
    "survival": "생존",
    "comment": "논평, 주석, 논평하다",
    "leap": "뛰다, 도약하다, 도약",
    "survey": "설문 조사, 조사하다, 둘러보다",
    "typical": "전형적인, 대표적인",
    "mere": "단지, ~에 불과한",
    "mechanic": "기계공",
    "mood": "기분, 분위기",
    "approve": "찬성하다, 승인하다",
    "rural": "시골의",
    "finance": "재정, 재무, 금융, 자금을 조달하다",
    "seek": "찾다, 추구하다, 노력하다",
    "operation": "작업, 운영, 수술",
    "crime": "범죄",
    "awful": "끔찍한, 지독한",
    "series": "연속, 시리즈물",
    "exhausted": "고갈된, 기진맥진한",
    "absolute": "완전한, 절대적인",
    "surround": "둘러싸다",
    "display": "전시하다, 나타내다, 전시",
    "policy": "정책, 수단, 방법",
    "mass": "많은 양, 덩어리, 집단, 대중",
    "committee": "(상급 기관에 소속된) 위원회",
    "accurate": "정확한",
    "arrange": "정리하다, 준비하다, 각색하다",
    "facility": "시설, 편의, 재능",
    "consult": "상담하다, 참고하다",
    "refer": "언급하다, 위탁하다",
    "attach": "붙이다, 첨부하다, 소속시키다",
    "recover": "회복하다, 되찾다",
    "reward": "보상, 보답하다",
    "enormous": "엄청난, 거대한",
    "domestic": "국내의, 가정의",
    "wealth": "부, 재산",
    "elementary": "초보의, 기초적인",
    "gap": "격자, 틈",
    "except": "~을 제외하고는, 제외하다",
    "journey": "여행",
    "plain": "평범한, 명백한",
    "downtown": "도심, 도심의, 도심지에"
};
const unit8 = {
    "previous": "앞의, 이전의",
    "produce": "생산하다, 제조하다",
    "remain": "여전히 ~이다, 남다, 남은 것",
    "break": "깨다, (기기 등을) 고장 내다",
    "slight": "약간의, 경미한",
    "include": "포함하다",
    "delay": "연기하다, 미루다, 지연",
    "file": "서류철, <컴퓨터> 파일, 서류철을 작성하다, (소송 등을) 제기하다",
    "ethic": "윤리",
    "instant": "즉각의, 즉석의, 순간",
    "reveal": "드러내다, 폭로하다",
    "breed": "낳다, 양육하다",
    "leisure": "여가, 자유시간, 한가한",
    "urban": "도시의",
    "witness": "목격자, 증인, 목격하다",
    "admit": "인정하다, 입장(입학)을 허락하다.",
    "muscle": "근육, 힘, 강제",
    "device": "장치, 고안, 방책",
    "suppose": "가정하다, 추측하다",
    "owe": "빚지고 있다, (명예·성공 등을) ~에 돌리다",
    "intend": "~할 작정이다, 의도하다",
    "aspect": "관점, 양상, 면",
    "potential": "잠재적인, 잠재력",
    "award": "수여하다, 상",
    "preserve": "보존하다, 보호하다",
    "spot": "지점, 얼룩, 발견하다, 얼룩지게 하다",
    "underground": "지하의, 비밀의, 지하",
    "consequence": "결과, 중요성",
    "target": "목표, 표적, 목표로 삼다",
    "unless": "~이 아닌 한, 만약 ~이 아니면",
    "accomplish": "이루다, 성취하다",
    "adopt": "채택하다, 입양하다",
    "unique": "독특한, 유일한",
    "slip": "미끄러지다, 살수하다, 종이 조각",
    "civilization": "문명",
    "row": "열, 줄, 배를 젓다",
    "horizon": "수평선, 지평선",
    "atmosphere": "대기, 분위기",
    "label": "꼬리표, 상표, 라벨을 붙이다, ~을…이라고 부르다",
    "decorate": "장식하다, ~에게 훈장을 주다"
};
const unit9 = {
    "identify": "~임을 확인하다, 식별하다, 동일시하다",
    "standard": "기준, 표준, 기준의, 표준의",
    "scale": "규모, 저울, 비늘",
    "evident": "명백한, 평범한",
    "seldom": "거의 ~않는",
    "secretary": "비서, 서기관, 장관",
    "basis": "기초, 원리",
    "automatic": "자동적인, 기계적인",
    "region": "지역",
    "rise": "상승, 오르다, 일어나다",
    "addict": "중독시키다. 중독자",
    "disappoint": "실망시키다",
    "artificial": "인공적인, 인조의",
    "possess": "소유하다, ~의 마음을 사로잡다",
    "substance": "물질, 본질, 실체",
    "realistic": "현실적인, 현실주의의",
    "encounter": "(우연히) 만나다, 마주침",
    "differ": "다르다. 의견을 달리하다",
    "principle": "원칙, 원리",
    "memorize": "기억하다",
    "physics": "물리학",
    "evaluate": "평가하다",
    "tremendous": "굉장한, 무시무시한",
    "application": "적용, 신청",
    "vote": "투표, 투표하다",
    "spread": "퍼짐, 확산, 퍼지다, 펼치다",
    "impact": "충격, 영향, 충격을 주다, 영향을 주다",
    "cooperate": "협력하다",
    "emit": "(빛, 열 소리등을) 방출하다",
    "request": "요청, 요청하다",
    "guarantee": "보증하다, 보증",
    "resist": "저항하다",
    "fulfill": "달성하다, 이행하다. 실현하다",
    "stink": "역겹다, 악취를 풍기다, 악취",
    "grant": "승인하다, 수여하다",
    "rely": "의지하다, 믿다",
    "permanent": "영원한, 영구적인",
    "emergency": "비상사태",
    "rid": "제거하다",
    "theme": "주제, 화제, 논제"
};
const unit10 = {
    "hesitate": "주저하다, 망설이다",
    "location": "장소, 위치",
    "restrict": "제한하다, 한정하다",
    "organism": "유기체, 생물, 생명체",
    "resolve": "결심하다, 해결하다, 분해하다",
    "offer": "제공하다, 제안하다",
    "distribute": "분배하다, 분포시키다",
    "rainforest": "(열대)우림",
    "circumstance": "상황, 환경",
    "interpret": "해석하다. 통역하다",
    "suitable": "적절한, 적합한",
    "curve": "곡선(길), 속임수",
    "annoy": "괴롭히다, 귀찮게 하다",
    "frighten": "겁먹게 하다",
    "estimate": "견적, 평가, 평가하다",
    "refuse": "거절하다",
    "adventure": "모험, 위험에 빠뜨리다",
    "entrance": "입장, 입구, 입학",
    "persuade": "설득하다",
    "perceive": "인지하다. 인식하다.",
    "recite": "암송하다",
    "gather": "모으다",
    "cabin": "오두막집, 객실, 선실",
    "gear": "장비, 기어, 맞게 조정하다",
    "ray": "광선",
    "release": "놓아주다, 방출하다, 발표하다, 석방, 발표",
    "rank": "등급, 지위, 매기다, 등급을 차지하다",
    "symphony": "교향곡, (소리의) 조화",
    "envy": "부러움, 부러워하다",
    "corporate": "회사의, 법인의",
    "alternative": "대안, 대안의",
    "retire": "은퇴하다",
    "appeal": "호소하다, 항의하다, 관심을 끌다, 호소, 항의, 매력",
    "identical": "동일한, 일란성의",
    "investment": "투자",
    "autograph": "서명, 서명하다",
    "slave": "노예",
    "harm": "손해, 손상, 해치다",
    "authority": "권위, 당국",
    "innocence": "결백, 무죄, 순진"
};
const unit11 = {
    "receive": "받다",
    "infant": "유아, 유아의, 미발달의",
    "calculate": "계산하다",
    "charity": "자비, 자선 단체, 구호물자",
    "accept": "받아들이다, (설명, 학성등을)인정하다",
    "depend": "의지하다",
    "whereas": "~인 반면에",
    "broad": "넓은, 광범위한, (빛 등이) 가득한",
    "treat": "여기다, 대우하다, 처리하다, 치료하다",
    "ignorant": "무식한, 모르는",
    "pure": "순수한",
    "extinct": "멸종된, 꺼진, 사라진",
    "household": "가정, 가정(가족)의",
    "refund": "반환, 환불, 환불하다",
    "continue": "계속하다",
    "institute": "연구소, 협회, 설립하다, 제정하다",
    "lately": "최근에",
    "ashamed": "부끄러워하는",
    "dense": "조밀한, 밀집한",
    "rescue": "구조하다, 구조",
    "destination": "목적지",
    "expand": "확장하다",
    "compete": "경쟁하다",
    "evolution": "진화",
    "hire": "고용하다",
    "genuine": "진짜의, 성실한",
    "status": "상태, 지위, 현상",
    "military": "군대의, 군대",
    "logic": "논리, 논리학",
    "gravity": "중력",
    "isolate": "고립시키다",
    "commit": "(죄를)저지르다, 전념(충실)하다, 맡기다",
    "sum": "총합, 합계",
    "conserve": "보존하다, 보호하다, 아끼다, 아껴쓰다.",
    "concept": "개념",
    "swing": "흔들(리)다, 진동하다, 그네",
    "sensible": "분별있는, 현명한",
    "marriage": "결혼, 혼인",
    "reproduce": "재생하다, 복제하다, 번식하다",
    "tone": "어조, 말투, 음, 색조"
};
const unit12 = {
    "cancel": "취소하다",
    "return": "돌아오다, 돌려주다, 귀환, 반납, 수익",
    "invitation": "초대, 초대장",
    "precise": "정확한",
    "formal": "공식적인, 정식의",
    "apparent": "분명한, 명백한",
    "departure": "출발",
    "visual": "시각의",
    "current": "현재의, 해류, 흐름",
    "agriculture": "농업",
    "leak": "새는 구멍, 새다, 누설하다",
    "portion": "일부, 부분, 분할하다",
    "trend": "추세, 경향",
    "particle": "입자, 극소량",
    "rite": "(종교적) 의식, 의례",
    "distinct": "별개의, 뚜렷한",
    "component": "(구성)요소, 구성하는",
    "poverty": "빈곤, 가난",
    "sculpture": "조각, 조각하다",
    "descend": "내려오다, 물려주다",
    "universal": "보편적인, 우주의",
    "surface": "표면, 수면, 지면",
    "eager": "갈망하는",
    "legal": "법률의, 합법의",
    "annual": "연례의, 1년의, 1년간의",
    "trap": "함정, 덫을 놓다, 막다",
    "demonstrate": "논증하다, 설명하다, 시위하다, 보여 주다",
    "companion": "동료, 동반자",
    "democracy": "민주주의, 민주주의 국가",
    "mature": "성숙한, 익은, 지불 만기의, 성숙해지다",
    "brilliant": "훌륭한, 명석한",
    "faith": "신념, 믿음",
    "aim": "겨냥하다, 조준",
    "spare": "여분의, 검소한, 용서하다, 남겨주다",
    "transfer": "이동하다, 옮기다, 갈아타다",
    "oppose": "반대하다",
    "desperate": "필사적인, 절망적인",
    "remote": "멀리 떨어진, 희박한, 드문",
    "offend": "기분을 상하게 하다, (범죄를) 저지르다",
    "awake": "깨어있는, 깨우다, 깨다"
};
const unit13 = {
    "option": "선택, 선택권",
    "insight": "통찰, 통찰력",
    "achieve": "(목적을) 달성하다, (명성을) 얻다",
    "civil": "시민의, 민간의",
    "pause": "중단, 중단하다, 잠시 멈추다.",
    "prove": "입증하다, (~임이) 판명되다",
    "lecture": "강의, 강의를 하다",
    "minor": "사소한, 소수의, 미성년자, 부전공, 부전공하다",
    "duty": "의무, 관세",
    "vigor": "활력",
    "organize": "조직하다, 구성하다, 정리하다",
    "chief": "주요한, 우두머리의, 우두머리",
    "complicated": "복잡한",
    "digest": "소화하다, (완전히) 이해하다, 요약",
    "shortage": "부족, 결함",
    "laboratory": "실험실, 실험(실)의",
    "arrive": "도착하다",
    "generous": "관대한, 넉넉한",
    "laundry": "세탁물",
    "transform": "변형시키다, 변환하다",
    "discipline": "훈련, 규율, 징계, 훈련(단련)하다, 징계하다",
    "forbid": "금지하다",
    "ultimate": "궁극적인, 최후의",
    "thrive": "번영하다, 발전하다, 잘 되다",
    "conversation": "대화, 회담, 좌담",
    "bet": "돈을 걸다, 내기를 하다, (~이)틀림없다, 내기",
    "royal": "왕족의, 왕의",
    "ruin": "파멸, 파산, 망치다, 파멸(파산)시키다",
    "worship": "예배하다, 숭배하다, 예배, 숭배",
    "evil": "사악한, 악",
    "scarce": "부족한, 드문",
    "afterward": "나중에, 그 후에",
    "client": "고객, (변호사 등의) 의뢰인",
    "insure": "보험을 계약하다, 안전하게 하다",
    "fancy": "공상, (일시적인)기호, 공상하다, 화려한",
    "surgery": "외과수술",
    "assign": "할당하다, 지정하다",
    "regulate": "규제하다, 조절하다",
    "shelf": "선반",
    "utility": "유용(성), (수도, 가스 등의) 공익사업"
};
const unit14 = {
    "necessity": "필수, 필수품, 필요",
    "yield": "생산하다, 양도하다, 굴복하다, 수확(물)",
    "decline": "감소, 쇠퇴, 감소하다, 쇠퇴하다, (정중히) 거절하다",
    "coincidence": "우연의 일치, 동시에 일어난 사건",
    "aside": "한쪽으로, 제쳐 두고",
    "contemporary": "동시대의, 현대의",
    "bless": "축복하다, 감사하다",
    "explain": "설명하다",
    "prior": "이전의, 우선하는",
    "tolerate": "참다, 용인하다",
    "measure": "측정하다, 측정, 수단",
    "abstract": "추상적인, 추상, 개요",
    "cottage": "오두막집",
    "correct": "올바른, 정확한, 바로잡다, 정정하다",
    "confirm": "입증(확인)하다, (결심을)굳게하다",
    "imitate": "모방하다",
    "prey": "먹이, 희생자",
    "defeat": "패배시키다, 패배",
    "illustrate": "설명하다, 예증하다, 삽화를 넣다",
    "fuse": "퓨즈, 도화선, 융합하다",
    "pupil": "학생, 눈동자",
    "intellect": "지성",
    "spice": "향신료, 양념",
    "tempt": "유혹하다, (관심을) 끌다",
    "inspire": "영감을 주다, 고무시키다, 격려하다",
    "dine": "만찬을 대접하다, 식사하다",
    "literally": "문자 그대로",
    "appropriate": "적절한",
    "resort": "휴양지, 의지, 의지하다, 자주 가다",
    "grab": "움켜쥐다, 움켜쥠",
    "propose": "제안하다, 청혼하다",
    "wreck": "난파선, 사고, 난파시키다",
    "document": "문서, 서류, 기록하다",
    "suspect": "의심하다, 용의자",
    "alien": "외국인, 외계인, 외국의, 이질적인",
    "prohibit": "금지하다",
    "install": "설치하다",
    "triumph": "승리, 승리하다",
    "scholarship": "학문, 장학금",
    "execute": "실행하다, 처형하다"
};
const unit15 = {
    "ensure": "확실하게 하다, 보증하다",
    "receipt": "영수증",
    "defect": "결점, (국가, 당 등을) 버리다",
    "trait": "특성, 특징",
    "modest": "겸손한, 알맞은",
    "virtual": "가상의, 사실상의",
    "compare": "비교하다",
    "address": "연설하다, 연설, 인사말",
    "inner": "내부의",
    "contrary": "반대의, 불리한, 반대의 것",
    "split": "찢다, (세로로) 쪼개다, 쪼개진, 분열",
    "supervise": "감독하다, 관리하다, 통제하다",
    "inhabit": "살다, 거주하다",
    "appear": "나타나다",
    "commute": "통근, 통근하다",
    "earthquake": "지진, (사회, 정치적) 대변동",
    "enroll": "입학하다, 등록하다",
    "debate": "토론, 토론하다",
    "abandon": "버리다, 포기하다",
    "conquer": "정복하다, 극복하다",
    "nevertheless": "그럼에도 불구하고",
    "seal": "도장, 봉인, 바다표범, 봉인하다",
    "greed": "탐욕",
    "contract": "계약하다, 수축하다, 계약서",
    "nutrition": "영양",
    "retail": "소매, 소매하다",
    "prejudice": "편견, 선입관",
    "register": "등록하다, 기재하다, 등록",
    "agency": "대리점",
    "nurture": "양육하다, 교육하다, 양육, 교육",
    "priest": "성직자",
    "elegant": "고상한, 우아한",
    "impose": "부과하다, 강요하다",
    "arise": "발생하다, 생겨나다",
    "modify": "변형하다, 수정하다",
    "masterpiece": "명작, 대작",
    "harsh": "거친, 가혹한",
    "drought": "가뭄",
    "criteria": "(pl.) 기준, 표준",
    "extraordinary": "비범한, 놀라운"
};
const unit16 = {
    "general": "일반적인, (육군, 공군, 해병대) 대장",
    "spill": "엎지르다, 흘리다, 엎질러짐, 유출",
    "usual": "보통의, 통상의",
    "routine": "일상적인 일, 일과, 일상적인",
    "eliminate": "제거하다, 삭제하다",
    "deny": "부인하다, 거절하다",
    "scream": "절규하다, 비명 지르다, 소리치다, 비명, 절규",
    "sensitive": "민감한, 예민한, 세심한",
    "swallow": "삼키다, 삼킴, 제비",
    "glare": "(눈부시게) 빛나다, 노려보다, 눈부신 빛, 노려봄",
    "tragic": "비극의, 비참한",
    "deprive": "박탈하다",
    "conscious": "의식하고 있는, 의도적인",
    "interfere": "방해하다, 간섭하다",
    "temporary": "일시적인, 임시의",
    "council": "협의회, 회의",
    "adolescent": "청소년, 청소년기의",
    "associate": "연관짓다, 교제하다, 동료",
    "arctic": "북극의",
    "capture": "붙잡다, 포획하다, 포획",
    "dilute": "묽은, 희석시키다",
    "figure": "생각(판단)하다, 계산하다, 수치, 계산, 형체",
    "dim": "흐릿한, 어두운, (불빛이) 흐려지다",
    "warehouse": "창고",
    "crew": "승무원",
    "barrier": "장벽, 장애물",
    "tradition": "전통, 관습",
    "pedestrian": "보행자, 보행자의",
    "glance": "흘긋 보다, 흘긋 봄",
    "irritate": "짜증나게 하다, 화나게 하다",
    "cruel": "잔인한, 고통을 주는",
    "fold": "접다, 포개다, 주름, (동물의) 우리",
    "trial": "재판, 실험, 시도",
    "tribe": "부족, 종족",
    "profound": "깊은, 심오한",
    "distinguish": "구별하다, 식별하다",
    "errand": "심부름, 잡일",
    "welfare": "복지",
    "statement": "진술, 성명서",
    "prevail": "우세하다, 만연하다"
};
const unit17 = {
    "widespread": "널리 퍼진",
    "result": "결과, (결과로서) 생기다",
    "fade": "사라지다",
    "progress": "진보하다, 전진하다, 진전, 진보",
    "weapon": "무기, 병기",
    "drastic": "격렬한, 과감한",
    "reinforcement": "강화, 보강",
    "wonder": "궁금해 하다, 놀라다, 경탄, 경이",
    "pile": "쌓아 올린 더미, 많은 양, 쌓아 올리다, 축적하다",
    "protect": "보호하다",
    "infection": "감염, 전염(병)",
    "stiffen": "굳어지다",
    "endanger": "위험에 빠뜨리다",
    "adjust": "조절하다, 조정하다",
    "peer": "동료, 또래",
    "renew": "새롭게 하다, 갱신하다",
    "germ": "미생물, 세균",
    "atom": "원자",
    "realize": "깨닫다, 실현하다",
    "enrich": "풍성하게 하다, 부유하게 하다",
    "noble": "귀족의, 고결한",
    "repair": "수선(수리)하다, (건강 등을) 회복하다, 수선(수리), 회복",
    "candidate": "후보자",
    "ideal": "이상적인, 이상",
    "crop": "작물, 수확",
    "ethnic": "인종의, 민족의",
    "foretell": "예언하다, 예고하다",
    "wholesale": "도매, 도매의",
    "debt": "빚, 부채",
    "representative": "대표, 국회의원(R~), 대표하는",
    "shift": "변화, 이동, 교대, 바꾸다, 이동하다",
    "excess": "초과, 초과량, 과도함, 초과한, 여분의",
    "strict": "엄한, 엄격한",
    "appliance": "(가정용) 기구, 장치",
    "furthermore": "게다가, 더욱이",
    "command": "명령, 지배력, 명령하다, 지휘하다",
    "ecosystem": "생태계",
    "fame": "명성, 유명인사",
    "oral": "구두의, 구술의",
    "drift": "표류, 표류하다"
};
const unit18 = {
    "avoid": "피하다",
    "outstanding": "뛰어난, 두드러진, 미해결의",
    "mislead": "잘못 인도하다, 오해하게 하다",
    "dedicate": "헌납하다, 바치다",
    "initial": "처음의, 초기의, 머리글자(이니셜)",
    "sink": "가라앉다",
    "entire": "전체의, 완전한, 전부, 전체",
    "confront": "직면하다",
    "beard": "턱수염",
    "haste": "급함, 서두름",
    "crush": "으깨다, 밀어 넣다",
    "destiny": "운명",
    "hardship": "고난, 어려움",
    "escape": "탈출하다, 벗어나다, 탈출, 도망",
    "valid": "타당한, 유효한",
    "dispose": "배치하다, 처리하다, 경향을 갖게 하다",
    "exist": "존재하다, 살아가다",
    "optimal": "최상의, 최적의",
    "hydrogen": "수소",
    "perspective": "관점, 견해, 원근법, 전망",
    "thread": "실, 실을 꿰다",
    "dynasty": "왕조, 왕가",
    "scatter": "흩뿌리다, 분산시키다",
    "gamble": "도박하다, 모험하다, 도박, 모험",
    "temper": "성질, 기질, 완화시키다",
    "undoubtedly": "의심할 여지없이, 확실히",
    "raft": "뗏목, 고무보트",
    "minimal": "최소의, 아주 적은",
    "soak": "적시다, 젖다, 흡수하다",
    "craft": "(수)공예, 기술, 선박, 비행기",
    "cease": "그만두다, 중지하다",
    "review": "재검토, 논평, 재검토하다",
    "ceiling": "천장, 상한선",
    "unify": "통합하다, 통일하다",
    "combat": "싸우다, 전투",
    "bump": "부딪치다, 충돌, 혹",
    "primary": "주요한, 최초(초기)의",
    "genre": "장르, 유형, 형식",
    "erase": "지우다, 없애다",
    "doom": "~할 운명이다, 운명, 비운, 파멸"
};
const unit19 = {
    "vital": "필수적인, 중요한, 생명 유지와 관련된",
    "incident": "일어난 일, 사건, 일어나기 쉬운",
    "session": "시간, 기간, 회의, (대학의) 학기",
    "obvious": "명백한, 분명한",
    "moderate": "온건한, 적당한",
    "budget": "예산, 예산안",
    "graze": "풀을 뜯다, 방목하다",
    "fragile": "부서지기 쉬운",
    "myth": "신화, 사회적 통념",
    "fur": "부드러운 털, 모피",
    "indifferent": "무관심한",
    "strain": "긴장시키다, 팽팽하게 하다, (너무 써서)상하게 하다, 긴장",
    "ingredient": "재료, 성분",
    "dismiss": "해고하다, 해산시키다, 묵살하다",
    "geometry": "기하학",
    "glacier": "빙하",
    "urge": "촉구하다, 강요하다",
    "celebrity": "명성, 유명 인사",
    "antique": "옛날의, 고대의, 고풍의, 골동품",
    "profit": "이익, 이윤, 이익을 얻다",
    "sphere": "구체, 구",
    "inherit": "상속하다, (유전으로)물려받다",
    "disgrace": "불명예, 수치",
    "crawl": "기어가다, 서행하다, 기어가기, 서행",
    "scratch": "긁다, 할퀴다, 긁힌, 자국, 찰과상",
    "diabetes": "당뇨병",
    "congestion": "밀집, 혼잡",
    "constitute": "구성하다, 제정하다, 설립하다",
    "flow": "흐르다, 흐름",
    "investigate": "조사하다, 수사하다",
    "barter": "물물교환하다, 물물교환, 교역품",
    "circular": "원의, 순환의",
    "chilly": "쌀쌀한, 냉담한",
    "ancestor": "조상, 선조",
    "fierce": "사나운, 맹렬한",
    "vague": "막연한, 모호한, 흐릿한",
    "rough": "거친, 난폭한, 대강의",
    "content": "만족하는, 내용(물), 목차",
    "obstacle": "장애물, 방해가 되는 것",
    "editorial": "사설, 논설, 편집자의"
};
const unit20 = {
    "abolish": "폐지하다",
    "assure": "보증하다, 확실하게 하다",
    "form": "형태, 종류, 형성하다",
    "gender": "성, 성별",
    "innovation": "혁신",
    "opponent": "반대자, 상대, 반대하는",
    "present": "현재의, 현재, 선물, 제출하다, 나타내다",
    "fertile": "비옥한, 기름진",
    "emperor": "황제",
    "dwell": "살다, 거주하다",
    "chore": "집안일, 허드렛일",
    "rehearsal": "리허설, 예행연습",
    "fossil": "화석",
    "glitter": "반짝이다, 반짝임",
    "carve": "조각하다, 새기다",
    "decay": "부패하다, 쇠퇴하다, 부패, 쇠퇴",
    "protein": "단백질",
    "backward": "후방에, 뒤쪽으로, 거꾸로",
    "translate": "번역하다, 옮기다",
    "refresh": "상쾌하게 하다, 새롭게 하다",
    "tissue": "(생물의 근육, 신경 등의) 조직",
    "lord": "군주",
    "substitute": "대리자, 대체물, 대체하다",
    "scan": "정밀 검사하다, 유심히 쳐다보다",
    "pottery": "도자기, 도예",
    "layer": "층, 겹",
    "property": "재산, 소유물, 부동산",
    "justify": "정당화하다",
    "polish": "닦다, 윤내다, (문장 등을) 다듬다",
    "flavor": "맛, 맛을 내다",
    "imprint": "(도장 등을) 찍다, 감명시키다, 찍은 자국, 인상",
    "heritage": "유산, 세습 재산",
    "strive": "노력하다, 애쓰다, 투쟁하다",
    "radiant": "빛나는, 아주 밝은",
    "exclaim": "(감탄하며) 외치다",
    "asset": "자산, 재산",
    "portray": "묘사하다, 설명하다, 초상을 그리다",
    "administer": "관리(운영)하다, 집행하다, 주다",
    "wage": "급료",
    "subscribe": "정기 구독하다"
};
const unit21 = {
    "merit": "장점, 공로, ~을 받을 만하다",
    "launch": "발사하다, (새로운 일을) 시작하다, 출시하다, 발사, 개시, 출시",
    "conference": "회담, 회의",
    "accuse": "고발하다, 비난하다",
    "enhance": "향상시키다",
    "intimate": "친밀한",
    "reception": "환영회, 접수",
    "overwhelm": "압도하다, 당황하게 하다",
    "apply": "적용하다",
    "majesty": "위엄, 장엄, 왕(M-)",
    "shrug": "(어깨를) 으쓱하다",
    "vicious": "사악한, 악의 있는",
    "cherish": "소중히 하다",
    "eternal": "영원한",
    "shrink": "축소하다, 수축하다",
    "colleague": "동료",
    "transmit": "전달하다",
    "discard": "버리다, 처분하다",
    "copper": "구리, 구리의, 구릿빛의",
    "orbit": "궤도, 궤도를 그리며 돌다",
    "famine": "굶주림, 기아",
    "pill": "알약",
    "immune": "면역성의, 면제된",
    "raw": "날것의, 가공하지 않은",
    "superior": "우월한, 상사",
    "string": "끈, 줄, 일련",
    "cope": "대처하다, 잘 처리하다",
    "loan": "대출, 대출금, 대출하다",
    "obedient": "순종하는, 유순한",
    "procedure": "절차, 과정",
    "bond": "결속, 속박, 약정, 채권",
    "angle": "각도, 모서리",
    "subtle": "미묘한, 교묘한",
    "depict": "묘사하다, 그리다",
    "radical": "과격한, 급진적인, 근본적인, 급진주의자",
    "caution": "조심, 주의, 주의하다",
    "persist": "고집하다, 지속하다",
    "reverse": "역, 반대, 역의, 반대의, 되돌리다",
    "cattle": "(집합적) 소",
    "therapy": "치료, 요법"
};
const unit22 = {
    "experience": "경험, 체험, 경험하다",
    "strategy": "전략",
    "attract": "(주의, 흥미 등을) 끌다",
    "hence": "그러므로, 지금부터",
    "architecture": "건축, 건축물",
    "territory": "영토, 영역",
    "wilderness": "황무지, 황야",
    "category": "범주",
    "funeral": "장례식, 장례의",
    "prefer": "선호하다",
    "outcome": "결과",
    "humiliation": "창피함, 굴욕",
    "ban": "금지하다, 금지",
    "flush": "(얼굴이) 붉어지다, 물이 쏟아져 나오다",
    "omit": "생략하다, 빼다",
    "despair": "절망, 절망하다",
    "alert": "기민한, 경계하는, 경계(태세), 경고하다",
    "compact": "소형의, 조밀한, 꽉 채우다",
    "likewise": "마찬가지로, 게다가",
    "astonish": "놀라게 하다",
    "panic": "갑작스러운 공포, 공황, 공황적인",
    "optimistic": "낙관적인, 낙천적인",
    "murder": "살인, 살인하다",
    "fundamental": "근본적인, 기본적인, 근본",
    "loyal": "충성스러운, 성실한",
    "humid": "(날씨가) 습기 있는, 눅눅한",
    "pretend": "~인 척하다, 주장하다",
    "graduate": "졸업하다, 졸업생, 대학원 학생",
    "delicate": "섬세한",
    "inflate": "부풀리다, 과장하다, (물가 등을) 인상하다",
    "adequate": "적당한",
    "physician": "의사, 내과 의사",
    "joint": "공동의, 연합의, 이음매, 관절",
    "via": "~을 거쳐서(경유해서), ~에 의하여",
    "passage": "통로, 통과, (인용문의) 한 절",
    "vessel": "(물건을 담는) 용기, 배, 선박, 혈관",
    "restore": "회복하다, 복구하다, 돌려주다",
    "passive": "수동적인, 수동형의",
    "marble": "대리석, 구슬, 대리석의",
    "classify": "분류하다"
};
const unit23 = {
    "prepare": "준비하다",
    "transaction": "거래, 처리",
    "sufficient": "충분한",
    "stable": "안정된, 마구간",
    "concern": "관련되다, 걱정하게 하다, 걱정, 관심사",
    "sympathy": "동정, 공감",
    "principle": "주요한, 제1의, (단체의) 장, 주역",
    "by-product": "부산물",
    "anxiety": "걱정, 불안, 열망",
    "edible": "먹을 수 있는, 식용의",
    "federal": "연방의, 연합의",
    "suffer": "고통 받다, 겪다",
    "trivial": "사소한",
    "tablet": "(의학) 정제, 알약, (평평한) 판",
    "trade": "교환하다, 무역",
    "liquid": "액체, 액체의",
    "contend": "싸우다, 주장하다, 경쟁하다",
    "anticipate": "예상하다, 기대하다",
    "outlook": "전망, 조망",
    "desert": "사막, 사막의, 불모의, 버리다, 도주하다",
    "infinite": "무한한",
    "roam": "배회하다, 돌아다니다",
    "decent": "제대로 된, 품위 있는",
    "behalf": "이익, 자기편",
    "distortion": "왜곡, 찌그러뜨림",
    "bud": "싹, 싹트다",
    "symbolic": "상징적인",
    "municipal": "지방(지자체)의, 시의",
    "phenomenon": "현상, 사건, 비범한 인물",
    "devote": "(노력, 시간 등을) 바치다",
    "peasant": "농민, 소작농",
    "diminish": "감소하다",
    "jealous": "질투하는",
    "exclude": "배제하다, 제외하다",
    "flexible": "융통성 있는, 유연한",
    "tenant": "세입자, 주민",
    "worthwhile": "~할 가치가 있는",
    "pavement": "보도, 포장도로",
    "nominate": "(후보자로) 지명(추천)하다, 임명하다",
    "sacred": "신성한, 성스러운"
};
const unit24 = {
    "support": "지지하다, 받치다, 부양하다, 지지, 지탱함, 부양",
    "revise": "개정하다",
    "suggest": "제안하다, 암시하다",
    "control": "지배하다, 제어하다, 지배, 제어",
    "mammal": "포유동물",
    "internal": "내부의",
    "resent": "분개하다, 화를 내다",
    "abrupt": "갑작스러운",
    "diverse": "다른, 다양한",
    "refine": "정제하다, 개선하다",
    "dynamic": "동적인, 역학의",
    "nerve": "신경",
    "prompt": "즉각적인, 촉구하다, 자극하다",
    "suspend": "매달다, 중지하다",
    "industry": "산업, 공업",
    "iceberg": "빙산",
    "monetary": "화페의",
    "superb": "최고의, 훌륭한",
    "gloom": "어둠, 우울",
    "distraction": "주의 산만, (정신을) 산만하게 하는 것, 기분 전환",
    "collapse": "무너지다, 붕괴하다, 붕괴",
    "trigger": "촉발하다, 유발하다, 방아쉬, 계기",
    "martial": "전쟁의, 군대의",
    "monologue": "독백",
    "deliberate": "의도적인, 신중한, 숙고하다",
    "plot": "줄거리, 음모, 음모를 꾸미다",
    "rod": "막대기, 회초리",
    "partial": "부분적인",
    "mutual": "서로의, 공통의",
    "priceless": "대단히 귀중한",
    "fate": "운명",
    "pursue": "추구하다, 쫓다",
    "Atlantic": "대서양, 대서양의",
    "weird": "이상한, 기묘한",
    "booth": "칸막이한 공간, 부스, 노점",
    "prescribe": "규정하다, (약을) 처방하다",
    "erupt": "분출하다, 폭발하다",
    "insult": "모욕하다, 모욕",
    "gaze": "뚫어지게 보다, 응시하다",
    "supreme": "최고, 최고의"
};
const unit25 = {
    "context": "경주(경쟁)하다, 질주하다, 경주",
    "complete": "완전한, 완벽한, 완료된, 완료하다",
    "race": "경주(경쟁)하다, 질주하다, 경주",
    "dominate": "지배하다",
    "vehicle": "탈것, 운송 수단",
    "complain": "불평하다, 항의하다",
    "brochure": "소책자, 브로셔",
    "force": "힘, 영향력, 강요하다",
    "nest": "둥지, 보금자리, 둥지를 틀다, (둥지에서) 살다",
    "gain": "얻다, 이익",
    "curriculum": "교육 과정, 커리큘럼",
    "sew": "꿰매다, 바느질하다",
    "masculine": "남자의, 남자다운",
    "frown": "눈살을 찌푸리다, 찡그린 얼굴",
    "astound": "놀라게 하다",
    "dictator": "독재자, 구술하는 사람",
    "assessment": "평가, 판단",
    "crucial": "중대한, 결정적인",
    "paralysis": "마비",
    "deck": "갑판",
    "cheer": "환호, 갈채, 환호(성원)하다",
    "miserable": "비참한, 불쌍한",
    "tease": "괴롭히다, 약올리다",
    "aggressive": "공격적인, 적극적인",
    "cure": "치료하다, 해결하다, 치유, 회복",
    "attribute": "~의 결과로 여기다, 속성",
    "foster": "육성하다, 촉진시키다, 수양의, 위탁의",
    "psychologist": "심리학자",
    "postpone": "연기하다, 뒤로 미루다",
    "rob": "훔치다, 강탈하다",
    "abuse": "남용, 욕설, 학대, 남용하다, 학대하다",
    "unemployed": "실업의, 실직한",
    "breakdown": "고장, 쇠약",
    "disguise": "변장하다, 숨기다, 변장, 은폐",
    "blueprint": "청사진",
    "rear": "뒤, 뒤의, 후방의, 기르다, 일으키다",
    "output": "생산(량), 산출(량)",
    "sermon": "설교",
    "sprout": "싹이트다, 자라나다, 싹",
    "tin": "양철, 주석"
};
const unit26 = {
    "reform": "개혁, 개혁하다",
    "deal": "다루다, 대처하다, 거래",
    "recruit": "모집하다, 징집하다, 신병, 신입 사원",
    "choke": "질식시키다, 숨이 막히다",
    "workshop": "작업장, 공동 연구회, 워크숍",
    "patient": "인내심 있는, 환자",
    "convention": "집회, 총회, 관습",
    "devastate": "황폐시키다",
    "reap": "수확하다",
    "overlook": "간과하다, 너그럽게 봐주다, 내려다보다",
    "troop": "무리, 떼, 군대, 군사",
    "reject": "거절하다, 버리다",
    "nourish": "영양분을 주다, 기르다",
    "bay": "만(灣)",
    "stun": "기절시키다. (놀람, 기쁨으로) 멍하게 하다. 놀래다",
    "particular": "특정한, 개개의, 사항, 상세",
    "bulletin": "게시, 게시물",
    "fluid": "유동체 (액체·기체의 총칭), 유동체의, 유동적인",
    "affair": "사건, 일",
    "dawn": "새벽, 이해되기 시작하다, 날이 새다",
    "hostile": "적대적인",
    "characteristic": "특징, 특색, 독특한, 특징적인",
    "respect": "존중하다, 존경, 관련",
    "await": "기다리다",
    "concrete": "구체적인, 콘크리트",
    "lease": "임대, 임대하다",
    "racial": "인종의",
    "variable": "변수, 변하기 쉬운, 변덕스러운",
    "satisfy": "만족시키다, 충족시키다",
    "rule": "지배, 규칙, 지배하다, 통치하다",
    "perseverance": "인내심",
    "fatal": "치명적인",
    "remove": "제거하다",
    "invert": "거꾸로 하다",
    "tension": "긴장, 불안, 긴장시키다.",
    "reign": "통치, 통치하다",
    "crack": "갈라진 틈, 금 가다",
    "startle": "깜짝 놀라게 하다",
    "discourage": "낙담시키다, 단념시키다",
    "compensate": "보상하다"
};
const unit27 = {
    "convert": "전환하다, 바꾸다",
    "strike": "치다, (머릿속에) 떠오르다",
    "suppress": "억압하다, 참다",
    "core": "핵심, 핵심의",
    "contribute": "공헌하다",
    "spear": "창",
    "renowned": "유명한, 명성 있는",
    "era": "시대",
    "withdraw": "(돈을) 인출하다, 철수시키다, 철회하다",
    "immigrate": "(타국에서) 이주하다",
    "dignity": "존엄",
    "notify": "통지하다, 알리다",
    "animate": "생기 있게 하다, 고무하다, 살아 있는",
    "prevent": "막다, 예방하다",
    "bilingual": "2개 국어의",
    "mischief": "해악, 장난",
    "discriminate": "차별하다, 구별하다",
    "exemplify": "예시하다, ~의 좋은 예가 되다",
    "adhere": "충실하다, 집착하다, 고수하다",
    "judge": "판단하다, 재판관",
    "peculiar": "독특한",
    "sake": "위함, 목적",
    "choke": "질식시키다, 숨이 막히다",
    "folktale": "민간 설화, 전설",
    "simultaneously": "동시에",
    "range": "정렬시키다, 범위",
    "groom": "신랑",
    "supernatural": "초자연적인",
    "tender": "부드러운, 입찰하다, 입찰",
    "instinct": "본능",
    "gigantic": "거대한",
    "meditate": "명상하다",
    "mow": "(풀을) 베다",
    "evolve": "발전하다, 진화하다",
    "chase": "쫓다, 추적하다",
    "afflict": "괴롭히다",
    "literate": "읽고 쓸 수 있는",
    "coherent": "통일성 있는, 조리 있는",
    "intolerable": "참을 수 없는",
    "fountain": "분수, 근원"
};
const unit28 = {
    "bold": "대담한, 선이 굵은",
    "compliment": "칭찬, 칭찬하다",
    "summit": "꼭대기, 정상",
    "troop": "무리, 떼, 군대, 군사",
    "alter": "바꾸다, 변경하다",
    "conceive": "생각해 내다, ~을 마음에 그리다",
    "durability": "내구성",
    "destroy": "파괴하다",
    "shallow": "얕은, 얇은, 피상적인, 천박한",
    "face": "직면하다, 얼굴, 표면",
    "promote": "증진하다, 승진시키다",
    "weep": "울다",
    "grasp": "붙잡다, 이해하다, 파악하다, 꽉 쥐기, 이해",
    "overall": "전반적인, 전체의, 작업복",
    "superstition": "미신",
    "colony": "식민지, 공동체, 군생",
    "absurd": "불합리한, 우스꽝스러운",
    "dormitory": "기숙사",
    "conduct": "수행하다, 실시하다, 행위, 안내",
    "prone": "~하는 경향이 있는",
    "conceal": "숨기다",
    "retreat": "퇴각, 후퇴, 퇴각하다, 후퇴하다",
    "compulsive": "강제적인, 강박의",
    "clinic": "전문 병원, 개인 병원",
    "banner": "깃발, 현수막",
    "formulate": "만들어내다, 공식화하다",
    "vow": "맹세, 맹세하다",
    "malnutrition": "영양실조",
    "relate": "관련시키다, 관련이 있다",
    "undergo": "겪다",
    "boast": "자랑하다, 떠벌리다",
    "neutral": "중립의, 공평한",
    "stain": "얼룩, 얼룩지게 하다",
    "incentive": "격려, 자극, 장려금, 격려하는, 자극하는",
    "float": "뜨다, 떠다니다, 부유물",
    "tendency": "경향, 추세",
    "applause": "박수갈채",
    "wrestle": "싸우다, (일과) 씨름하다, 레슬링하다",
    "sensation": "감각, 느낌, 대사건 (센세이션)",
    "Confucian": "공자의, 유교의"
};
const unit29 = {
    "draft": "밑그림, 원고, 초안을 그리다",
    "crude": "가공하지 않은, 조잡한",
    "supplement": "보충, 보충하다",
    "velocity": "속도",
    "tame": "길들이다, 길들여진",
    "molecule": "분자",
    "manage": "~을 잘 해내다, 다루다",
    "dismay": "실망시키다, 낙담시키다, 걱정, 실망",
    "diagnose": "진단하다",
    "adapt": "적응하다, 적응시키다",
    "reservoir": "저장소, 저수지",
    "conform": "적합하게 하다, 순응시키다",
    "spacious": "넓은, 훤히 트인",
    "weave": "엮다, 짜다",
    "boundary": "경계, 경계선",
    "motive": "동기 (행동의 원인)",
    "prominent": "현저한, 저명한",
    "inferior": "열등한",
    "rigid": "완고한",
    "archaeology": "고고학",
    "subtract": "빼다",
    "impulse": "충동, 추진",
    "utmost": "최대한의, 최대한도",
    "proficient": "숙달된",
    "accumulate": "모으다, 축적하다",
    "embody": "구현하다, 구체화하다",
    "equity": "공평",
    "violate": "침해하다, 위반하다",
    "ambitious": "야심있는",
    "intact": "본래대로의, 손상되지 않은",
    "borrow": "빌리다",
    "attend": "출석하다, 보살피다",
    "trim": "잘라내다, 다듬다",
    "navigate": "길을 찾다, 항해(비행)하다",
    "tray": "쟁반",
    "consist": "(부분·요소로) 이루어지다",
    "ceremony": "의식, 식, 의례",
    "attack": "공격하다, 공격",
    "confine": "한정하다, 감금하다, 한계",
    "dispatch": "급파하다, 발송하다, 급파, 발송"
};
const unit30 = {
    "diameter": "지름, 직경",
    "anecdote": "일화, 비화",
    "propriety": "적절성, 예의바름",
    "blame": "비난하다, ~의 탓으로 돌리다, 비난, 책망",
    "earn": "(평판을) 얻다, 벌다",
    "pledge": "약속, 맹세, 약속하다, 맹세하다",
    "cost": "(비용이) 들다, 비용, 대가",
    "geology": "지질학",
    "detect": "발견하다, 감지하다",
    "temperate": "절제하는, (기후가) 온화한",
    "soar": "높이 치솟다",
    "mock": "조롱하다, 가짜의",
    "disclose": "드러내다, 폭로하다",
    "exhibit": "전시하다, 보여 주다, 전시, 전시품",
    "symptom": "증상",
    "invent": "발명하다",
    "awkward": "서투른, 어색한, 꼴사나운",
    "grind": "갈다, 빻다",
    "expose": "드러내다, (비밀을) 폭로하다, 노출시키다",
    "closet": "벽장",
    "damp": "축축한, 습기",
    "script": "손으로 쓰기, 대본",
    "possibility": "가능성, 가망",
    "discuss": "토론하다",
    "sibling": "형제자매, 동기",
    "lay": "(물건을) 놓다, (알을) 낳다",
    "flourish": "번영하다, 번창하다",
    "discharge": "배출, 내보냄, 방전, 배출하다, 내보내다, 해고하다",
    "thorough": "철저한",
    "undertake": "수행하다, (일을) 떠맡다, 착수하다",
    "panel": "토론자단, 패널, 넓은 직사각형의 합판",
    "linguistic": "언어의, 언어학의",
    "remedy": "치료, 요법",
    "feed": "먹이를 주다, 부양하다",
    "sophomore": "(대학·고등학교의) 2학년생",
    "remind": "상기시키다",
    "sole": "유일한",
    "pillar": "기둥",
    "explode": "폭발하다",
    "illusion": "환상, 착각"
};
const unit31 = {
    "regret": "후회하다, 한탄하다, 유감, 후회",
    "submit": "복종시키다. 복종하다. 제출하다.",
    "divine": "신(神)의, 신성한",
    "revenue": "수입, 수익",
    "corrupt": "부정한, 부패한, 타락시키다.",
    "separate": "분리하다",
    "factual": "실제의",
    "swamp": "늪지",
    "expedition": "탐험(대)",
    "abnormal": "비정상적인",
    "storage": "저장, 저장고",
    "revive": "되살아나다",
    "consistent": "일관된, 모순이 없는",
    "motion": "운동, 움직임, 몸짓, 몸짓으로 지시(신호)하다",
    "patent": "특허, 특허권, ~의 특허를 얻다",
    "virtue": "미덕",
    "deadline": "마감 시간, 최종 기한",
    "equator": "적도",
    "cognitive": "인식의, 인지력 있는",
    "hinder": "방해하다",
    "humble": "겸손한, 비천한",
    "bounce": "(공이) 튀다, 뛰어오르다",
    "imprison": "투옥하다",
    "enlist": "(군인을) 모집하다, 도움을 얻다",
    "hygiene": "위생, 위생학",
    "upcoming": "다가오는",
    "trace": "흔적, 흔적을 쫓다",
    "pulse": "맥박",
    "locate": "~에 위치하다, (위치를)찾아내다",
    "controversy": "논란, 논쟁",
    "flattery": "아첨",
    "regard": "~으로 여기다, 관계, 고려",
    "convenience": "편의, 편리",
    "carbon": "탄소",
    "rush": "돌진하다, 갑자기 일어나다",
    "contaminate": "오염시키다",
    "external": "외부의",
    "herd": "짐승의 떼",
    "allocate": "할당하다, 배분하다",
    "gorgeous": "화려한, 아주 멋진"
};
const unit32 = {
    "confess": "고백하다",
    "subjective": "주관적인, 주격의",
    "casual": "우연한, 무심결의, 격식을 차리지 않는",
    "acknowledge": "인정하다",
    "accord": "일치하다, 일치, 협정",
    "immense": "막대한",
    "extract": "추출하다, 추출물",
    "sewage": "하수",
    "reconciliation": "화해",
    "explore": "탐험하다, 탐사하다",
    "warrant": "보증, 영장, 보증하다",
    "complement": "보완하다, 보충물",
    "ceramic": "도자기, 도자기의",
    "license": "면허, 인가, 면허[인가]를 내주다",
    "emerge": "나오다, 나타나다, 드러나다",
    "halt": "정지, 일시 멈춤, 정지하다, 정지시키다",
    "pierce": "꿰뚫다, ~에 구멍을 뚫다",
    "ponder": "심사숙고하다",
    "burglar": "(주거침입)강도",
    "stroke": "뇌졸중, 강타",
    "lottery": "복권, 추첨",
    "certificate": "증명서",
    "transplant": "이식, 이식하다",
    "cluster": "(사람들의)무리, (과일·꽃의) 송이, 성단",
    "plea": "탄원, 간청, 변명",
    "derive": "끌어내다, ~에서 비롯되다",
    "plague": "전염병",
    "ultrasound": "초음파",
    "deluxe": "호화로운, 사치스러운",
    "convey": "전달하다, 나르다",
    "depth": "깊이",
    "evaporate": "증발하다",
    "lame": "절름발이의",
    "intelligence": "지능, 지성",
    "sour": "신맛이 나는",
    "repetitive": "반복성의",
    "oppress": "억압하다",
    "leftover": "나머지의, 남은, 남은 음식",
    "embrace": "포옹, 포옹하다, 받아들이다",
    "blade": "칼날"
};
const unit33 = {
    "abundant": "풍부한",
    "duplicate": "복제품, 이중으로 하다, 복제하다",
    "spoil": "망치다, 상하게 하다, 버릇없게 키우다",
    "altitude": "고도, 높이",
    "glimpse": "흘긋 봄, 흘긋 보다, 깨닫다",
    "blend": "혼합, 혼합하다",
    "swell": "부풀다, 팽창",
    "grief": "큰 슬픔",
    "beverage": "음료",
    "warrior": "용사",
    "shrub": "관목",
    "slice": "얇은 조각, 얇게 썰다",
    "exotic": "이국적인",
    "arrogant": "거만한",
    "vanish": "사라지다",
    "outbreak": "(전쟁, 질병 등의) 발발, 폭동",
    "predominant": "뛰어난, 우세한",
    "cozy": "아늑한",
    "recommend": "추천하다",
    "auction": "경매, 경매에 부치다",
    "obsess": "강박 관념을 갖다, (망상이) 사로잡다",
    "suitor": "소송인, 구혼자",
    "rational": "이성적인, 합리적인",
    "discreet": "분별 있는, 사려 깊은",
    "pioneer": "개척자, 개척자의, 개척하다",
    "assert": "주장하다, 행사하다",
    "undo": "원상태로 돌리다, (매듭을) 풀다",
    "inevitable": "피할 수 없는",
    "elaborate": "정교한, 공들인",
    "toss": "던지다",
    "retain": "유지[보유]하다",
    "maximize": "최대화하다, 최대한으로 활용하다",
    "buildup": "축적",
    "machinery": "(집합적) 기계",
    "sacrifice": "희생하다, 희생시키다, 희생, 제물",
    "auditorium": "강당",
    "linger": "오래 머물다, 계속되다",
    "neglect": "무시하다, 소홀, 무시",
    "feedback": "반응, 피드백",
    "radioactive": "방사성의"
}
const unit34 = {
    "impair": "손상시키다",
    "metaphor": "은유, 은유법",
    "dispense": "나누어 주다, 내놓다",
    "bruise": "타박상, 멍 타박상을 입히다, 멍들게 하다",
    "attorney": "변호사",
    "sanitation": "하부 구조, 뼈대, 틀",
    "heredity": "유전, 유전 형질",
    "naive": "순진한",
    "shed": "떨구다, 흘리다, 발산하다",
    "metropolitan": "수도권의, 대도시의",
    "shield": "방패, 보호물, 보호하다",
    "ecology": "생태학",
    "record": "기록하다, 녹음하다, 기록, 증언",
    "expel": "쫓아내다",
    "plow": "쟁기, 쟁기질하다",
    "prolong": "연장하다",
    "fluent": "유창한",
    "margin": "가장자리",
    "induce": "유도하다, 설득하다",
    "interior": "내부, 내부의",
    "ornament": "장식, 장식하다",
    "probe": "조사하다, 탐사선",
    "vibrate": "진동하다, 흔들다",
    "speculate": "사색하다, 투기하다",
    "versus": "~대, ~와 대비하여",
    "pregnant": "임신한",
    "epidemic": "전염병, 유행병",
    "precede": "~에 앞서다, 먼저 일어나다",
    "breathtaking": "아슬아슬한, 숨 막히는",
    "foundation": "기초, 토대, 재단",
    "stimulate": "자극하다, 고무하다",
    "fabric": "구조, 조직, 직물",
    "overturn": "전복시키다, 전복",
    "ripe": "익은",
    "framework": "뼈대, 틀, 체제",
    "urgent": "긴급한, 다급한",
    "settle": "정착하다, 정착시키다, 결정하다",
    "conflict": "충돌하다, 갈등, 충돌",
    "vapor": "증기, 증발하다",
    "tuition": "수업료"
};
const unit35 = {
    "literature": "문학, 문예, 문헌",
    "loop": "고리",
    "quote": "인용하다",
    "inhale": "(숨을) 들이쉬다",
    "prospect": "가능성, 전망",
    "anchor": "닻, 앵커, 닻을 내리다",
    "reference": "참조, 참고, 언급",
    "compound": "화합물, 합성의, 혼합하다",
    "withstand": "견디다",
    "implement": "도구, 실행하다",
    "anonymous": "익명의",
    "collide": "충돌하다",
    "memorial": "기념물, 기념관",
    "vacant": "빈, 비어 있는",
    "technical": "기술[기법]의, 전문적인",
    "summon": "소집하다, 소환하다",
    "orchard": "과수원",
    "proportion": "비율, 부분",
    "antibiotic": "항생 물질",
    "overtake": "따라잡다",
    "resemble": "닮다, 비슷[유사]하다",
    "wander": "(정처없이) 돌아다니다, 유랑, 방랑",
    "compassion": "연민, 동정",
    "preoccupation": "몰두, 집착, 선취",
    "paste": "풀, 반죽, 풀칠하다, 붙이다",
    "provoke": "선동하다, 자극하다",
    "wicked": "사악한",
    "sprain": "(발목·손목 등을) 삐다",
    "propaganda": "선전 활동, 선전",
    "consistent": "일관된, 모순이 없는",
    "disrupt": "~을 혼란에 빠뜨리다, 방해하다",
    "solitary": "혼자의, 외로운, 고독한",
    "bury": "파묻다",
    "rust": "녹, 녹슬다, 녹이 슬게 하다",
    "discuss": "토론하다",
    "referee": "심판, 심판하다",
    "sector": "분야, 지역, 부채꼴",
    "boost": "상승, 밀어올림, 밀어올리다, (생산량을) 증가하다",
    "gymnastics": "체육, 체조",
    "gross": "총합, 총합의, 엄청난, ~의 총이익을 올리다"
};
const unit36 = {
    "last": "계속하다, 끈기",
    "tariff": "관세, 관세를 부과하다",
    "beloved": "사랑스러운",
    "lyric": "노래 가사, 서정시, 서정적인",
    "yeast": "효모, 발효하다",
    "skyscraper": "마천루, 고층 건물",
    "inquire": "묻다, 조사하다",
    "spade": "삽",
    "vacuum": "진공, 진공청소기, 진공청소기로 청소하다",
    "migrate": "이동하다, 이주하다",
    "spectacle": "광경",
    "surplus": "과잉, 나머지, 과잉의, 나머지의",
    "simulate": "가장하다, 모의 실험(훈련)하다",
    "integration": "통합, (수학)적분",
    "hypothesis": "가설",
    "affirm": "단언하다",
    "fortress": "(대규모의) 요새",
    "reed": "갈대, 갈대의",
    "cue": "단서, 신호",
    "mole": "사마귀, 점",
    "divide": "나누다, 분리하다, 분할",
    "inborn": "타고난",
    "overlap": "겹치다, 중복",
    "fatigue": "피로, 피곤하게 하다",
    "clone": "복제 생물, 클론, 복제하다",
    "peel": "~의 껍질을 벗기다, 껍질",
    "ease": "진정시키다, 편함, 용이함",
    "overcome": "압도하다, 극복하다",
    "fund": "기금, 자금을 제공하다",
    "bias": "편견",
    "vaccine": "백신, (컴퓨터) 바이러스 예방 프로그램",
    "tread": "밟다, 걷다, 밟음",
    "vomit": "토하다",
    "prophecy": "예언",
    "correspond": "일치하다, 서신 왕래하다",
    "cling": "달라붙다, 집착하다",
    "mutation": "돌연변이, 변화",
    "obscure": "불분명한, 이해하기 어려운, 무명의",
    "tyrant": "폭군, 전제 군주",
    "odd": "이상한, 홀수의"
};
const unit37 = {
    "intriguing": "아주 흥미로운",
    "restrain": "억제하다, 구속하다",
    "bundle": "묶음, 꾸러미",
    "enclose": "동봉하다, 에워싸다",
    "insert": "삽입하다",
    "keen": "날카로운, 예민한",
    "constrict": "죄다, 위축시키다",
    "aid": "돕다, 도움, 조력",
    "reputation": "평판, 명성",
    "measurement": "측정, 측량, 치수",
    "originate": "시작되다, 비롯하다",
    "flour": "밀가루",
    "manipulate": "조종하다, 조작하다",
    "experiment": "실험, 실험하다",
    "patriot": "애국자",
    "interchange": "교환, 교차점(I.C.), 교환하다",
    "intuitive": "직관적인, 직관에 의한",
    "garment": "의복",
    "spontaneous": "자발적인, 자연히 일어나는",
    "vertical": "수직의",
    "testify": "검증하다, 증명하다, 증언하다",
    "mentor": "조언자",
    "vivid": "생생한",
    "pasture": "목초지, 목장",
    "crust": "껍질, 지각",
    "comprehend": "이해하다, 포함하다",
    "plunge": "뛰어들다, 던져 넣다",
    "nasty": "더러운, 불쾌한",
    "appreciate": "이해하다, 감상하다, 고맙게 생각하다",
    "emigrate": "(타국으로)이주하다",
    "deed": "행위, 업적",
    "skinny": "피골이 상접한, 마른",
    "grill": "석쇠, 석쇠로 굽다, 심문하다",
    "canal": "수로, 운하",
    "curse": "저주, 저주하다",
    "adverse": "거스르는, 반대의, 부정적인",
    "censorship": "검열",
    "forehead": "이마",
    "appetite": "식욕, 욕망, 욕구",
    "flaw": "결점, 흠"
};
const unit38 = {
    "outgoing": "외향적인",
    "verbal": "말의, 구두의",
    "liberate": "해방시키다, 자유롭게 하다",
    "segregation": "인종 차별, 분리",
    "advance": "나아가게 하다, 진척시키다, 전진, 증진",
    "contemplate": "~을 숙고하다, 응시하다",
    "underlying": "밑에 놓인, 기초를 이루는",
    "academic": "학문적인, 학구적인",
    "stem": "생기다, 일어나다, 줄기, 대",
    "irrigation": "관개",
    "consecutive": "연속적인, 일관된",
    "superficial": "표면상의, 피상적인",
    "refuge": "피난, 피난처, 위안",
    "swear": "맹세하다, 욕하다",
    "allergy": "알레르기",
    "norm": "규범, 기준, 표준",
    "endeavor": "노력, 노력하다",
    "erect": "세우다, 똑바로 선",
    "feminine": "여성의, 여성스러운",
    "drowsy": "졸리는",
    "inspect": "검사하다, 점검하다",
    "carriage": "마차, 탈것",
    "primitive": "원시의, 초기의, 미개의, 원시인",
    "compress": "압축하다",
    "govern": "다스리다, 통치하다, 지배[좌우]하다",
    "cemetery": "공동묘지",
    "shatter": "산산이 부서지다, 파편",
    "exaggerate": "과장하다, 과장해서 말하다",
    "random": "무작위의, 임의의",
    "feast": "즐겁게(기쁘게)하다, 축제(일), 잔치",
    "commemorate": "기념하다",
    "steep": "가파른, 경사가 급한",
    "multitask": "다중작업을 하다",
    "toxic": "유독한, 중독의",
    "stare": "응시하다, 노려보다",
    "chronic": "만성적인, 장기간의",
    "designate": "지정하다, 가리키다",
    "dramatic": "연극의, 극적인",
    "intense": "강렬한",
    "propaganda": "선전 활동, 선전"
};
const unit39 = {
    "numerous": "다수의, 수많은",
    "shiver": "떨림, 떨다",
    "retarded": "(정서·지능·학력) 발달이 뒤진",
    "ongoing": "진행, 진행 중의",
    "mention": "언급하다, 언급",
    "executive": "집행의, 경영의, 임원, 경영진",
    "chaos": "혼돈, 무질서",
    "microscope": "현미경",
    "belonging": "(pl.) 소유물, 소지품",
    "vulnerable": "취약한, 상처 입기 쉬운",
    "implication": "함축, 암시",
    "alley": "오솔길, 골목길",
    "authentic": "진짜의, 진정한",
    "compel": "강요하다, ~하게 만들다",
    "transition": "변천, 과도기",
    "index": "지수, 색인",
    "incline": "내키게 하다, 기울이다, 경사",
    "attain": "달성하다",
    "innate": "천부적인, 본질적인",
    "ingenuity": "솜씨, 독창력",
    "upset": "마음이 상한, 당황한, 뒤엎다, 전복, 혼란",
    "stretch": "늘이다, 뻗다, 신축성",
    "seize": "잡다, 이해하다",
    "screw": "나사, 나사로 고정하다",
    "savage": "야만적인, 잔인한, 야만인",
    "province": "지방, (광역 행정 구역으로서의) 도, 분야",
    "coordinate": "조정하다, 동등한",
    "deficient": "부족한, 불완전한",
    "privilege": "특권, 특권을 주다",
    "preview": "미리 보기, 예고편, 시사회",
    "equivalent": "동등한, 상당하는",
    "shelter": "피난하다, 보호하다, 피난처",
    "throughout": "(장소의) 도처에, (시간의) 처음부터 끝까지",
    "outlaw": "금지하다, 법적으로 무효화하다, 무법자",
    "squeeze": "짜내다",
    "breakthrough": "비약적 발전, 돌파구",
    "consent": "동의, 허락, 동의하다",
    "orphan": "고아",
    "negotiate": "협상하다",
    "nuisance": "귀찮은 사람, 성가신 것"
};
const unit40 = {
    "recipe": "조리법, 비법",
    "deceive": "속이다",
    "sweep": "휩쓸다, 청소하다",
    "profile": "옆모습, 인물 소개, 옆얼굴",
    "enterprise": "기업, 사업",
    "successive": "연속되는, 상속의",
    "paradox": "역설, 패러독스",
    "surpass": "능가하다",
    "correlation": "상관관계, 상호 관련",
    "magnitude": "거대함, 중요성, (지진) 진도",
    "aesthetics": "미학",
    "earnest": "진지한, 진심",
    "tremble": "떨다",
    "slaughter": "도살하다, 도살, 대학살",
    "surrender": "넘겨주다, 포기하다, 항복하다",
    "philosophy": "철학",
    "deplete": "고갈시키다, 격감시키다",
    "admire": "감탄하다, 존경하다",
    "starvation": "아사, 기아, 궁핍",
    "summon": "소집하다, 소환하다",
    "afford": "~할 여유가 있다",
    "blunt": "무뚝뚝한, 퉁명스러운, 둔감한, 무딘",
    "sprint": "단거리 경주, 전력 질주, 전력 질주하다",
    "passerby": "통행인, 지나가는 사람",
    "tense": "팽팽한, 긴장한, 긴장시키다",
    "boil": "끓다, 삶다",
    "timber": "목재",
    "collaborate": "협력하다",
    "stance": "서 있는 자세, 태도",
    "blow": "불다, 바람에 날리다",
    "ballot": "투표, 투표용지, 투표하다",
    "division": "분할, 나누기, (대학의) 학부, (군대) 사단",
    "acquaintance": "아는 사이, 교제",
    "amplify": "확대하다, 증폭시키다",
    "contradict": "부정하다, 반박하다, 모순되다",
    "burst": "터뜨리다, 파열, 폭발",
    "cast": "내던지다, (빛을) 발하다",
    "falsify": "잘못을 입증하다",
    "psychic": "초능력이 있는, 초자연적인, 무당, 영매",
    "paddle": "노, 노를 젓다"
};
const unit41 = {
    "steer": "조종하다, 인도하다",
    "affection": "애정, 감정",
    "bid": "말하다, 명령하다, 입찰하다, 입찰",
    "compost": "혼합물, 퇴비",
    "temperament": "기질, 성질",
    "rent": "임대하다, 집세",
    "shred": "갈기갈기 찢다, 째다",
    "unpredictable": "예측할 수 없는",
    "tribute": "감사[존경]의 표시, 증정물, 진상품, 조세",
    "artery": "동맥, 간선 도로",
    "inherent": "내재하는, 타고난, 고유의",
    "harass": "괴롭히다, 희롱하다, 침략하다",
    "narrative": "이야기, 서술, 이야기의",
    "assemble": "모으다, 조립하다, 소집하다",
    "spike": "대못, 대못을 박다",
    "sneak": "살금살금 움직이다, 몰래 움직이다",
    "sophisticated": "세련된, 정교한",
    "handle": "다루다",
    "enlightenment": "계몽, 개화, 깨달음",
    "cosmetic": "화장품, 미용의",
    "gracious": "상냥한, 우아한",
    "aspire": "열망하다, 동경하다",
    "obstruct": "막다, 방해하다",
    "patrol": "순찰, 순찰병, 순찰하다",
    "accelerate": "가속하다, 촉진하다",
    "heatstroke": "일사병, 열사병",
    "oval": "달걀 모양의, 타원형의, 타원체",
    "veteran": "경험이 많은, 베테랑, 퇴역 군인",
    "trail": "오솔길, 자국",
    "vocation": "직업, 천직",
    "vegetarian": "채식주의자, 채식주의자의, 채식의",
    "decode": "해독하다",
    "fellow": "사나이, 동료, 동료의",
    "mandate": "명령하다, 위임하다",
    "perish": "죽다, 소멸하다",
    "inseparable": "불가분의, 떼어 낼 수 없는",
    "domain": "영역, 영토, 분야",
    "statesman": "정치가",
    "connotation": "함축, 내포",
    "stereotype": "인습, 고정관념"
};
const unit42 = {
    "hallow": "속이 빈, 오목한 움푹한 곳",
    "structural": "구조(상)의, 조직(상)의",
    "mortgage": "저당, 주택 융자, (담보) 대출",
    "inject": "주사하다, 도입하다",
    "crisis": "위기, 중대 국면",
    "latter": "나중 쪽의, 후자의",
    "illuminate": "밝게 비추다, 계몽하다, 설명하다",
    "mimic": "모방하다, 흉내를 잘 내는, 모조의",
    "unearth": "발굴하다, 발견하다",
    "wail": "울부짖다, 울부짖음",
    "shudder": "떨다, 몸서리치다",
    "stride": "성큼성큼 걷다, 성큼성큼 걷기, 진보, 발전",
    "applicant": "신청자, 지원자",
    "disprove": "오류를 증명하다, 논박하다",
    "disturb": "방해하다, 어지럽히다, 혼란케 하다",
    "hemisphere": "반구체, (지구·천체의) 반구",
    "recur": "재발하다, 되풀이하다",
    "elastic": "탄력 있는, 융통성 있는",
    "counterpart": "상대, 대응하는 것(사람)",
    "stubborn": "완고한, 고집이 센",
    "suicide": "자살",
    "lure": "유혹하다, 매력",
    "underprivileged": "경제적·사회적으로 권리가 적은, 혜택받지 못한",
    "morale": "사기, 의욕",
    "examine": "검사하다, 진찰하다",
    "compromise": "타협하다, 타협",
    "foremost": "주요한, 으뜸가는",
    "precaution": "조심, 예방 조치",
    "torture": "고문, 고문하다",
    "entrust": "위임하다, 맡기다",
    "sway": "흔들림, 흔들리다",
    "religious": "종교(상)의, 종교적인",
    "obligation": "의무, 계약, 채무",
    "pest": "해충, 역병, 귀찮은 것",
    "subdue": "정복하다, 진압하다, 완화하다",
    "incorporate": "법인회사로 만들다, 통합시키다",
    "regime": "정권, 제도",
    "terminate": "끝내다, 종결짓다",
    "rebel": "반역자, 반역을 일으키다",
    "meanwhile": "한편, 그 동안에"
};
const unit43 = {
    "folklore": "민속, 민속 신앙, 신화",
    "vast": "막대한, 방대한",
    "preliminary": "예비의, 임시의, 예선, 사전 준비",
    "theft": "도둑질, (야구)도구",
    "painkiller": "진통제",
    "amend": "수정하다, 고치다",
    "recess": "휴식, 휴업, 구석진 곳",
    "exploit": "(부당하게) 이용하다, 착취하다, 위업",
    "autonomy": "자치, 자율",
    "outfit": "옷[복장], 장비, 공급하다, 준비하다",
    "mourn": "슬퍼하다, 애도하다",
    "evoke": "일깨우다, 이끌어 내다",
    "burden": "짐, 부담, ~에게 짐을 지우다",
    "latitude": "위도, 위선",
    "patch": "헝겊 조각, 좁은 땅, 헝겊 조각을 붙이다",
    "maternal": "어머니의, 모계의, 모국어의",
    "pharmacy": "약국, 약학",
    "marine": "해양의, 바다의",
    "prestigious": "명성이 있는, 고급의, 일류의",
    "friction": "마찰, 의견 충돌",
    "defend": "방어하다, 수비하다",
    "fraud": "사기, 속임, 사기꾼",
    "easygoing": "태평스러운, 안이한",
    "insomnia": "불면증",
    "intermediate": "중간의, 중간물",
    "transport": "수송[운송]하다, 수송",
    "paradigm": "패러다임, 이론적 틀",
    "charge": "요금을 청구하다, 채우다",
    "rapid": "빠른, 신속한",
    "premature": "조숙한, 조산한, 시기상조의",
    "pollute": "오염시키다, 더럽히다",
    "altruism": "이타주의",
    "fiber": "섬유(질)",
    "irony": "반어법, 아이러니",
    "spectator": "관객, 구경꾼",
    "medieval": "중세의",
    "analogy": "유추, 비슷함",
    "snatch": "잡아채다, 날치기하다",
    "anthropology": "인류학",
    "outline": "개요를 말하다, 윤곽을 보여 주다, 개요, 윤곽"
};
const unit44 = {
    "slogan": "선전 문구, 슬로건",
    "composure": "침착, 평정",
    "incurable": "불치의, 구제 불능의, 불치 환자",
    "parallel": "평행의, 유사한, 평행선, 유사하다",
    "indulge": "탐닉하다, 충족시키다, 제멋대로 하게 하다",
    "meadow": "목초지, 초원",
    "venture": "모험하다, 모험",
    "deflect": "빗나가다, 빗나가게 하다, 막다",
    "adorable": "귀여운, 사랑스러운",
    "complacent": "(스스로) 만족해하는, 현실에 안주하는",
    "explicit": "명백한, 분명한",
    "sturdy": "견고한, 강건한",
    "primate": "영장류",
    "patron": "후원자, 단골 손님, 고객",
    "endure": "참다, 인내하다, 견디다",
    "manifest": "명백하게 하다, 증명하다, 명백한",
    "imperial": "제국의, 황제의",
    "duration": "지속, 지속 기간",
    "populate": "거주시키다",
    "frugal": "검소한, 절약하는",
    "registration": "기재, 등록",
    "rejoice": "크게 기뻐하다",
    "comprise": "포함하다, 구성하다",
    "textile": "직물의, 방직의",
    "lurk": "숨다, 잠복하다",
    "humanity": "인류, 인간성, 인간애",
    "approximate": "(수량 등이) ~에 가까워지다, 대략의",
    "revenge": "복수, 복수하다",
    "sarcastic": "비꼬는, 풍자적인",
    "terrain": "지형, 지역, 분야, 범위",
    "toll": "사용세, 통행료, 요금으로 징수하다",
    "warfare": "전쟁, 교전 상태",
    "mortal": "죽을 운명의, 치명적인",
    "spouse": "배우자",
    "crispy": "바삭바삭한, 부서지기 쉬운",
    "statistical": "통계적인, 통계학상의",
    "rubbish": "쓰레기, 폐기물",
    "stimulus": "자극, 격려",
    "clumsy": "어색한, 서투른",
    "subsequent": "그 후의, ~에 이어 일어나는"
};
const unit45 = {
    "relevant": "관련된, 적절한",
    "predator": "포식자, 약탈자, 육식 동물",
    "drain": "물을 빼내다, 소모시키다",
    "countless": "셀 수 없는, 무수한",
    "condense": "농축하다, 요약하다",
    "post": "(벽 따위에)붙이다, 우편",
    "poise": "균형을 잡다, 균형, 평정",
    "disciple": "문하생, 제자",
    "gust": "돌풍, 질풍",
    "collective": "집합적인, 집단적인, 집단",
    "scope": "(관찰.활동의) 범위, 시야, 조사하다",
    "compatible": "양립할 수 있는, 모순이 없는",
    "border": "가장자리, 국경, 접하다",
    "frontier": "국경, 국경의, 최첨단의",
    "withhold": "억누르다, 억제하다, 보류하다",
    "verdict": "판결, 결정",
    "stall": "마구간, 우리, 핑계, 핑계를 대다",
    "apparatus": "장치, 기구, 조직",
    "hail": "환호하다, 경의를 표하다",
    "obstruct": "막다, 방해하다",
    "vanity": "허영심, 허무함",
    "firsthand": "직접, 바로, 직접의",
    "obesity": "(병적인) 비만, 비대",
    "dilemma": "진퇴양난, 딜레마, 궁지",
    "render": "~이 되게 하다, 주다, 표현하다",
    "indispensable": "필수 불가결한, 없어서는 안 될 것",
    "outdated": "시대에 뒤진, 구식의",
    "bother": "일부러 ~하다, 괴롭히다",
    "counteract": "(효력을) 중화시키다, 약화시키다",
    "static": "정적인, 고정된",
    "sustain": "지탱하다, 유지하다",
    "posture": "태도, 자세",
    "discourse": "강연, 담화",
    "bribe": "뇌물, 뇌물을 주다",
    "juggle": "잘 처리하다, 저글링하다",
    "perspiration": "땀, 노력",
    "retention": "보유, 기억(력)",
    "valiant": "용감한, 용맹스러운",
    "distress": "고민, 고통, ~을 괴롭히다",
    "nursery": "욱아실, 탁아소, 양성소"
};
const unit46 = {
    "encircle": "에워싸다, 둘러싸다",
    "notion": "개념, 의견",
    "disgust": "혐오감, 역겹게 하다",
    "fragment": "일부분, 부서진 조각",
    "oversee": "감독하다, 감시하다",
    "creep": "기다, (덩굴 등이) 얽히다, 포복, 서행",
    "clarify": "명백히 하다",
    "contagious": "전염성의, 감염성의",
    "deterioration": "악화, (가치의) 하락",
    "currency": "통화, 통용",
    "janitor": "문지기, 관리인, 잡역부",
    "blush": "얼굴을 붉히다, 부끄러워하다",
    "intervene": "사이에 끼어들다, 개입하다, 방해하다",
    "nomad": "유목민, 방랑자",
    "cuisine": "(독특한) 요리, 요리법",
    "dare": "감히 ~하다",
    "solvent": "용해력이 있는, 지불 능력이 있는, 용제",
    "cultivate": "경작하다, 양성하다, 계발하다",
    "ascent": "상승, 오름",
    "advocate": "옹호자, 지지자, 지지하다",
    "spur": "자극, 고무, 박차를 가하다",
    "discern": "식별하다, 분별하다, ~을 인식하다",
    "scheme": "계획, 체계, 계획하다",
    "weigh": "비난, 비난하다",
    "publicity": "널리 알려짐, 명성, 광고, 선전",
    "declare": "선언하다",
    "brisk": "활발한, 번창하는, 상쾌한",
    "exile": "망명, 망명자, 망명시키다",
    "whisper": "속삭이다, 속삭임",
    "fling": "내던지다, 돌진하다",
    "deviation": "변경, 일탈",
    "dissolve": "용해하다, 해산하다, 해소하다",
    "constraint": "강제, 압박, 거북스러움",
    "itch": "가려움, 가렵다, (~하고 싶어) 못 견디다",
    "unanimous": "만장일치의, 합의의",
    "delude": "속이다, 착각하게 하다",
    "dehydrate": "탈수하다, 건조시키다",
    "underneath": "~의 아래에, 밑에",
    "metabolism": "물질대사, 신진대사",
    "appoint": "임명하다, (시간, 장소를) 정하다"
};
const unit47 = {
    "pinch": "~을 꼬집다, 집다, 괴롭히다",
    "punctual": "시간을 지키는, 기한을 지키는",
    "arbitrary": "임의적인, 독단적인",
    "catastrophe": "대참사, 큰 재앙",
    "exert": "(힘·지식 등을) 쓰다, 발휘하다",
    "aviate": "비행하다, (비행기를) 조종하다",
    "headquarters": "본부(단수 취급)",
    "rectangular": "직사각형의, 직각의",
    "delegate": "파견하다, 사절, 대표",
    "elect": "선출하다",
    "thorn": "가시, 괴로움의 원인",
    "empathize": "공감하다, 감정 이입을 하다",
    "expertise": "전문 지식[기술]",
    "renovate": "~을 새롭게 하다, 수리하다",
    "wrench": "렌치 (너트를 죄는 기구), 비틀기, 비틀다, 삐다",
    "interval": "간격, 틈",
    "degrade": "저하시키다, 강등시키다, 분해하다",
    "retort": "반박, 말대꾸, 반박하다, 말대꾸하다",
    "asthma": "천식",
    "realm": "왕국, 영역",
    "segment": "부분, 분할하다",
    "coexist": "공존하다",
    "hospitality": "환대, 후한 대접",
    "estate": "소유지, 재산",
    "displace": "옮겨 놓다, 대신하다, 쫓아내다",
    "cripple": "~을 불구로 만들다, 지체 부자유자",
    "drawback": "문제점, 장애",
    "tactics": "방안, 전술",
    "dread": "공포, 무서워하다",
    "dispute": "논쟁, 분쟁, 토의하다",
    "console": "위로하다",
    "stack": "더미, 쌓다, 쌓이다",
    "cynical": "냉소적인, 비꼬는",
    "reprove": "꾸짖다, 책망하다",
    "verify": "검증하다, 입증하다",
    "engross": "열중하게 하다",
    "bulk": "크기, 부피, 대부분",
    "despise": "경멸하다",
    "manuscript": "손으로 쓴 것, 필사본, 원고",
    "flee": "달아나다, 도망치다"
};
const unit48 = {
    "prehistoric": "선사 시대의",
    "barrel": "통, (석유) 1배럴",
    "predecessor": "앞서 있었던 것, 선배, 전임자",
    "alienate": "소외시키다, 멀리하다",
    "proclaim": "선언하다, 증명하다",
    "subordinate": "하급의, 부차적인, 하급자, 경시하다",
    "furnish": "(필요한 것을) 제공하다, 갖추다",
    "fume": "연기, 연기 나다",
    "staple": "주요한, 주요 산물",
    "dimension": "크기, 치수, 규모, 차원",
    "dispersal": "분산, 확산",
    "eloquent": "웅변의, 표현이 풍부한",
    "innermost": "가장 깊숙한, 가장 깊은 부분",
    "hazardous": "위험한, 모험적인",
    "skull": "두개골",
    "detergent": "세제",
    "brutal": "야만적인, 짐승 같은, 잔혹한",
    "rash": "발진, 뾰루지, 무분별한, 성급한",
    "bypass": "우회하다, 우회로",
    "accommodate": "수용하다, 숙박시키다",
    "tact": "재치, 기지",
    "monotonous": "단조로운, 지루한",
    "perpetual": "영구의, 끊임없는",
    "eligible": "적격의, 적임자",
    "legacy": "유산",
    "melancholy": "우울한, 우울함",
    "simplicity": "간단, 단순, 소박",
    "hierarchy": "계급(제), 위계",
    "reside": "거주하다, 속하다",
    "enact": "법제화하다, 제정하다",
    "burnout": "극도의 피로, 쇠진, 연소 종료",
    "legitimate": "타당한, 정당한, 합법의",
    "shuffle": "질질 끌며 걷다, 뒤섞다",
    "summarize": "요약하다",
    "eject": "쫓아내다, 배출하다",
    "intersection": "교차(로), 횡단",
    "quest": "탐색, 탐구",
    "linear": "직선의, 길이의, 1차(원)의",
    "landslide": "산사태, 압도적인 승리",
    "plausible": "그럴듯한, 말재주 있는"
};
const unit49 = {
    "endow": "부여하다, 기부하다",
    "extrinsic": "외적인, 외부의",
    "merge": "합병하다, 차차 변하다",
    "frantic": "광란의, 미친",
    "moan": "신음, 신음하다, 불평하다",
    "merchandise": "(집합적) 상품",
    "respectively": "각각, 저마다",
    "yearn": "그리워하다, 열망하다",
    "conviction": "확신, 유죄 판결",
    "stout": "뚱뚱한, (옷 등이) 튼튼한",
    "reckon": "세다, 계산하다, 생각하다",
    "enchant": "매혹하다, ~에 마법을 걸다",
    "entail": "수반하다, 의미하다, 필요로 하다",
    "demolish": "파괴하다, 폐지하다",
    "degenerate": "퇴보하다, 타락하다",
    "sentiment": "감상, 정서",
    "offspring": "자식, 새끼, 성과",
    "detest": "혐오하다, 미워하다",
    "tackle": "(일·문제를) 다루다, 도구, (축구의) 태클",
    "defy": "물리치다, (공공연히) 반항하다, 무시하다",
    "inference": "추론",
    "refraction": "(빛·소리 따위의) 굴절",
    "dusk": "땅거미, 어스름",
    "detach": "떼어 내다, 분리하다",
    "antagonist": "적대자, 라이벌",
    "thrust": "밀다, 밀치다",
    "creed": "신념, (종교의) 교의",
    "equate": "동일시하다, 일치하다",
    "misplace": "잘못 두다",
    "auditory": "귀의, 청각의",
    "missionary": "선교사",
    "cosmopolitan": "세계적인, 세계주의의, 세계인, 국제인",
    "secondhand": "중고의, 간접적인",
    "multiple": "복합적인, 다수의, 다양한, ＜수학＞ 배수",
    "embed": "깊숙이 박다, 깊이 간직하다",
    "propel": "나아가게 하다, 추진하다",
    "reptile": "파충류",
    "erosion": "부식, 침식",
    "feat": "위업, 공적",
    "utensil": "가정용품, 기구, 용구"
};
const unit50 = {
    "penetrate": "침투하다, 꿰뚫다",
    "intrude": "방해하다, 침범하다",
    "notable": "주목할 만한",
    "grumble": "불평하다, 으르렁거리다, 불평",
    "landfill": "쓰레기 매립지",
    "scrutiny": "(면밀한) 조사",
    "reckless": "부주의한, 무모한",
    "synthetic": "＜화학＞ 합성의",
    "productive": "생산적인, 다산의",
    "outset": "착수, 시작",
    "peril": "위험, 위기",
    "pitfall": "함정, 위험",
    "kidnap": "유괴, 납치하다",
    "liable": "책임이 있는, ~할 것 같은, ~하기 쉬운",
    "insane": "정신 이상의, 비상식적인",
    "rage": "격노",
    "radius": "반지름",
    "hybrid": "혼합, 잡종",
    "uncover": "폭로하다, (비밀 등을) 알아내다",
    "limb": "사지, 팔다리",
    "setback": "좌절, 차질",
    "prudent": "신중한, 빈틈없는",
    "solidify": "굳어지다, 굳히다, 확고히 하다",
    "grudge": "원한, 유감",
    "lessen": "줄(이)다",
    "tangle": "얽히게 하다, 혼란시키다",
    "subsidy": "보조금, 장려금",
    "ambiguous": "애매모호한, 두 가지 뜻으로 해석 가능한",
    "enthusiasm": "열광, 열정, 열의",
    "bankruptcy": "파산",
    "pollination": "(식물) 수분 (작용)",
    "prosper": "번영하다. 번창하다",
    "phase": "상, 면, 양상, 단계",
    "veterinarian": "수의사",
    "counterattack": "반격, 역습, 반격하다, 역습하다",
    "cumulative": "누적되는, 점증적인",
    "infrastructure": "사회 기반 시설, (단체 등의) 하부 조직(구조)",
    "wound": "부상하게 하다, 부상",
    "discrete": "분리된, 별개의",
    "fluctuation": "변동, 오르내림, 요동"
};


// 모든 유닛 데이터를 window 객체에 추가
for (let i = 1; i <= 50; i++) {
    window[`unit${i}`] = eval(`unit${i}`);
}

let mergedObject = {}; // 전역 변수로 선언

function generateQuiz() {
    const startNumber = parseInt(document.getElementById('startInput').value);
    const endNumber = parseInt(document.getElementById('endInput').value);

    if (isNaN(startNumber) || isNaN(endNumber) || startNumber < 1 || endNumber > 50 || startNumber > endNumber) {
        alert("Please enter valid unit numbers between 1 and 50.");
        return;
    }

    const objectsArray = [];
    for (let i = startNumber; i <= endNumber; i++) {
        const unit = window[`unit${i}`];
        if (unit) {
            objectsArray.push(unit);
        }
    }

    mergedObject = Object.assign({}, ...objectsArray); // 전역 변수에 할당
    const shuffledKeys = shuffleArray(Object.keys(mergedObject));
    const quizContainer = document.querySelector('.quiz-container');
    quizContainer.innerHTML = '';

    shuffledKeys.forEach((key, index) => {
        const correctAnswer = mergedObject[key];
        const options = [correctAnswer, ...getRandomOptions(mergedObject, correctAnswer)];
        const shuffledOptions = shuffleArray(options);

        const questionHtml = `
            <div>
                <strong>${index + 1}. ${key}</strong>
                <select name="question${index + 1}" class="pl">
                    <option value="0" selected>Select the correct meaning</option>
                    ${shuffledOptions.map(option => `<option value="${option}">${option}</option>`).join('')}
                </select>
            </div>
        `;

        quizContainer.insertAdjacentHTML('beforeend', questionHtml);
    });

    document.getElementById('submitBtn').style.display = 'block';
}

function getRandomOptions(obj, correctAnswer) {
    const values = Object.values(obj).filter(value => value !== correctAnswer);
    const randomValues = [];

    while (randomValues.length < 3) {
        const randomValue = values[Math.floor(Math.random() * values.length)];
        if (!randomValues.includes(randomValue)) {
            randomValues.push(randomValue);
        }
    }

    return randomValues;
}

function shuffleArray(array) {
    const shuffledArray = array.slice();
    for (let i = shuffledArray.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [shuffledArray[i], shuffledArray[j]] = [shuffledArray[j], shuffledArray[i]];
    }
    return shuffledArray;
}

function gradeQuiz() {
    const quizContainer = document.querySelector('.quiz-container');
    const selects = quizContainer.querySelectorAll('select');
    let correctCount = 0;
    const incorrectAnswers = [];

    selects.forEach((select, index) => {
        const selectedValue = select.value;
        const questionKey = select.previousElementSibling.textContent.split('. ')[1];
        const correctAnswer = mergedObject[questionKey];

        if (selectedValue === correctAnswer) {
            correctCount++;
        } else {
            incorrectAnswers.push({ questionKey, correctAnswer });
        }
    });

    const totalQuestions = selects.length;
    const scorePercentage = (correctCount / totalQuestions) * 100;
    document.getElementById('results').innerHTML = `
        <div class="centered">You scored ${correctCount} out of ${totalQuestions} (${scorePercentage.toFixed(2)}%)</div>
        <br><br>
        <strong>Incorrect Answers:</strong>
        <table>
            <thead>
                <tr>
                    <th>English Word</th>
                    <th>Correct Meaning</th>
                </tr>
            </thead>
            <tbody>
                ${incorrectAnswers.map(answer => `
                    <tr>
                        <td>${answer.questionKey}</td>
                        <td class="toggle-meaning" onclick="toggleMeaning(this)">${answer.correctAnswer}</td>
                    </tr>
                `).join('')}
            </tbody>
        </table>
    `;
}
